using System;
using System.Collections.Generic;

namespace Scolarite.Domain.entities
{
    public partial class EspPvClasse
    {
        public string CodeCl { get; set; }
        public string IdEt { get; set; }
        public string Annee { get; set; }
        public DateTime DatePv { get; set; }
        public string TypeCol1 { get; set; }
        public string IdCol1 { get; set; }
        public string NomCol1 { get; set; }
        public decimal? MoyCol1 { get; set; }
        public string EtatCol1 { get; set; }
        public string TypeCol2 { get; set; }
        public string IdCol2 { get; set; }
        public string NomCol2 { get; set; }
        public decimal? MoyCol2 { get; set; }
        public string EtatCol2 { get; set; }
        public string TypeCol3 { get; set; }
        public string IdCol3 { get; set; }
        public string NomCol3 { get; set; }
        public decimal? MoyCol3 { get; set; }
        public string EtatCol3 { get; set; }
        public string TypeCol4 { get; set; }
        public string IdCol4 { get; set; }
        public string NomCol4 { get; set; }
        public decimal? MoyCol4 { get; set; }
        public string EtatCol4 { get; set; }
        public string TypeCol5 { get; set; }
        public string IdCol5 { get; set; }
        public string NomCol5 { get; set; }
        public decimal? MoyCol5 { get; set; }
        public string EtatCol5 { get; set; }
        public string TypeCol6 { get; set; }
        public string IdCol6 { get; set; }
        public string NomCol6 { get; set; }
        public decimal? MoyCol6 { get; set; }
        public string EtatCol6 { get; set; }
        public string TypeCol7 { get; set; }
        public string IdCol7 { get; set; }
        public string NomCol7 { get; set; }
        public decimal? MoyCol7 { get; set; }
        public string EtatCol7 { get; set; }
        public string TypeCol8 { get; set; }
        public string IdCol8 { get; set; }
        public string NomCol8 { get; set; }
        public decimal? MoyCol8 { get; set; }
        public string EtatCol8 { get; set; }
        public string TypeCol9 { get; set; }
        public string IdCol9 { get; set; }
        public string NomCol9 { get; set; }
        public decimal? MoyCol9 { get; set; }
        public string EtatCol9 { get; set; }
        public string TypeCol10 { get; set; }
        public string IdCol10 { get; set; }
        public string NomCol10 { get; set; }
        public decimal? MoyCol10 { get; set; }
        public string EtatCol10 { get; set; }
        public string TypeCol11 { get; set; }
        public string IdCol11 { get; set; }
        public string NomCol11 { get; set; }
        public decimal? MoyCol11 { get; set; }
        public string EtatCol11 { get; set; }
        public string TypeCol12 { get; set; }
        public string IdCol12 { get; set; }
        public string NomCol12 { get; set; }
        public decimal? MoyCol12 { get; set; }
        public string EtatCol12 { get; set; }
        public string TypeCol13 { get; set; }
        public string IdCol13 { get; set; }
        public string NomCol13 { get; set; }
        public decimal? MoyCol13 { get; set; }
        public string EtatCol13 { get; set; }
        public string TypeCol14 { get; set; }
        public string IdCol14 { get; set; }
        public string NomCol14 { get; set; }
        public decimal? MoyCol14 { get; set; }
        public string EtatCol14 { get; set; }
        public string TypeCol15 { get; set; }
        public string IdCol15 { get; set; }
        public string NomCol15 { get; set; }
        public decimal? MoyCol15 { get; set; }
        public string EtatCol15 { get; set; }
        public string TypeCol16 { get; set; }
        public string IdCol16 { get; set; }
        public string NomCol16 { get; set; }
        public decimal? MoyCol16 { get; set; }
        public string EtatCol16 { get; set; }
        public string TypeCol17 { get; set; }
        public string IdCol17 { get; set; }
        public string NomCol17 { get; set; }
        public decimal? MoyCol17 { get; set; }
        public string EtatCol17 { get; set; }
        public string TypeCol18 { get; set; }
        public string IdCol18 { get; set; }
        public string NomCol18 { get; set; }
        public decimal? MoyCol18 { get; set; }
        public string EtatCol18 { get; set; }
        public string TypeCol19 { get; set; }
        public string IdCol19 { get; set; }
        public string NomCol19 { get; set; }
        public decimal? MoyCol19 { get; set; }
        public string EtatCol19 { get; set; }
        public string TypeCol20 { get; set; }
        public string IdCol20 { get; set; }
        public string NomCol20 { get; set; }
        public decimal? MoyCol20 { get; set; }
        public string EtatCol20 { get; set; }
        public string TypeCol21 { get; set; }
        public string IdCol21 { get; set; }
        public string NomCol21 { get; set; }
        public decimal? MoyCol21 { get; set; }
        public string EtatCol21 { get; set; }
        public string TypeCol22 { get; set; }
        public string IdCol22 { get; set; }
        public string NomCol22 { get; set; }
        public decimal? MoyCol22 { get; set; }
        public string EtatCol22 { get; set; }
        public string TypeCol23 { get; set; }
        public string IdCol23 { get; set; }
        public string NomCol23 { get; set; }
        public decimal? MoyCol23 { get; set; }
        public string EtatCol23 { get; set; }
        public string TypeCol24 { get; set; }
        public string IdCol24 { get; set; }
        public string NomCol24 { get; set; }
        public decimal? MoyCol24 { get; set; }
        public string EtatCol24 { get; set; }
        public string TypeCol25 { get; set; }
        public string IdCol25 { get; set; }
        public string NomCol25 { get; set; }
        public decimal? MoyCol25 { get; set; }
        public string EtatCol25 { get; set; }
        public string TypeCol26 { get; set; }
        public string IdCol26 { get; set; }
        public string NomCol26 { get; set; }
        public decimal? MoyCol26 { get; set; }
        public string EtatCol26 { get; set; }
        public string TypeCol27 { get; set; }
        public string IdCol27 { get; set; }
        public string NomCol27 { get; set; }
        public decimal? MoyCol27 { get; set; }
        public string EtatCol27 { get; set; }
        public string TypeCol28 { get; set; }
        public string IdCol28 { get; set; }
        public string NomCol28 { get; set; }
        public decimal? MoyCol28 { get; set; }
        public string EtatCol28 { get; set; }
        public string TypeCol29 { get; set; }
        public string IdCol29 { get; set; }
        public string NomCol29 { get; set; }
        public decimal? MoyCol29 { get; set; }
        public string EtatCol29 { get; set; }
        public string TypeCol30 { get; set; }
        public string IdCol30 { get; set; }
        public string NomCol30 { get; set; }
        public decimal? MoyCol30 { get; set; }
        public string EtatCol30 { get; set; }
        public string TypeCol31 { get; set; }
        public string IdCol31 { get; set; }
        public string NomCol31 { get; set; }
        public decimal? MoyCol31 { get; set; }
        public string EtatCol31 { get; set; }
        public string TypeCol32 { get; set; }
        public string IdCol32 { get; set; }
        public string NomCol32 { get; set; }
        public decimal? MoyCol32 { get; set; }
        public string EtatCol32 { get; set; }
        public string TypeCol33 { get; set; }
        public string IdCol33 { get; set; }
        public string NomCol33 { get; set; }
        public decimal? MoyCol33 { get; set; }
        public string EtatCol33 { get; set; }
        public string TypeCol34 { get; set; }
        public string IdCol34 { get; set; }
        public string NomCol34 { get; set; }
        public decimal? MoyCol34 { get; set; }
        public string EtatCol34 { get; set; }
        public string TypeCol35 { get; set; }
        public string IdCol35 { get; set; }
        public string NomCol35 { get; set; }
        public decimal? MoyCol35 { get; set; }
        public string EtatCol35 { get; set; }
        public string TypeCol36 { get; set; }
        public string IdCol36 { get; set; }
        public string NomCol36 { get; set; }
        public decimal? MoyCol36 { get; set; }
        public string EtatCol36 { get; set; }
        public string TypeCol37 { get; set; }
        public string IdCol37 { get; set; }
        public string NomCol37 { get; set; }
        public decimal? MoyCol37 { get; set; }
        public string EtatCol37 { get; set; }
        public string TypeCol38 { get; set; }
        public string IdCol38 { get; set; }
        public string NomCol38 { get; set; }
        public decimal? MoyCol38 { get; set; }
        public string EtatCol38 { get; set; }
        public string TypeCol39 { get; set; }
        public string IdCol39 { get; set; }
        public string NomCol39 { get; set; }
        public decimal? MoyCol39 { get; set; }
        public string EtatCol39 { get; set; }
        public string TypeCol40 { get; set; }
        public string IdCol40 { get; set; }
        public string NomCol40 { get; set; }
        public decimal? MoyCol40 { get; set; }
        public byte? NbHeureCol1 { get; set; }
        public byte? NbHeureCol2 { get; set; }
        public byte? NbHeureCol3 { get; set; }
        public byte? NbHeureCol4 { get; set; }
        public byte? NbHeureCol5 { get; set; }
        public byte? NbHeureCol6 { get; set; }
        public byte? NbHeureCol7 { get; set; }
        public byte? NbHeureCol8 { get; set; }
        public byte? NbHeureCol9 { get; set; }
        public byte? NbHeureCol10 { get; set; }
        public byte? NbHeureCol11 { get; set; }
        public byte? NbHeureCol12 { get; set; }
        public byte? NbHeureCol13 { get; set; }
        public byte? NbHeureCol14 { get; set; }
        public byte? NbHeureCol15 { get; set; }
        public byte? NbHeureCol16 { get; set; }
        public byte? NbHeureCol17 { get; set; }
        public byte? NbHeureCol18 { get; set; }
        public byte? NbHeureCol19 { get; set; }
        public byte? NbHeureCol20 { get; set; }
        public byte? NbHeureCol21 { get; set; }
        public byte? NbHeureCol22 { get; set; }
        public byte? NbHeureCol23 { get; set; }
        public byte? NbHeureCol24 { get; set; }
        public byte? NbHeureCol25 { get; set; }
        public byte? NbHeureCol26 { get; set; }
        public byte? NbHeureCol27 { get; set; }
        public byte? NbHeureCol28 { get; set; }
        public byte? NbHeureCol29 { get; set; }
        public byte? NbHeureCol30 { get; set; }
        public byte? NbHeureCol31 { get; set; }
        public byte? NbHeureCol32 { get; set; }
        public byte? NbHeureCol33 { get; set; }
        public byte? NbHeureCol34 { get; set; }
        public byte? NbHeureCol35 { get; set; }
        public byte? NbHeureCol36 { get; set; }
        public byte? NbHeureCol37 { get; set; }
        public byte? NbHeureCol38 { get; set; }
        public byte? NbHeureCol39 { get; set; }
        public byte? NbHeureCol40 { get; set; }
        public decimal? CoefCol1 { get; set; }
        public decimal? CoefCol2 { get; set; }
        public decimal? CoefCol3 { get; set; }
        public decimal? CoefCol4 { get; set; }
        public decimal? CoefCol5 { get; set; }
        public decimal? CoefCol6 { get; set; }
        public decimal? CoefCol7 { get; set; }
        public decimal? CoefCol8 { get; set; }
        public decimal? CoefCol9 { get; set; }
        public decimal? CoefCol10 { get; set; }
        public decimal? CoefCol11 { get; set; }
        public decimal? CoefCol12 { get; set; }
        public decimal? CoefCol13 { get; set; }
        public decimal? CoefCol14 { get; set; }
        public decimal? CoefCol15 { get; set; }
        public decimal? CoefCol16 { get; set; }
        public decimal? CoefCol17 { get; set; }
        public decimal? CoefCol18 { get; set; }
        public decimal? CoefCol19 { get; set; }
        public decimal? CoefCol20 { get; set; }
        public decimal? CoefCol21 { get; set; }
        public decimal? CoefCol22 { get; set; }
        public decimal? CoefCol23 { get; set; }
        public decimal? CoefCol24 { get; set; }
        public decimal? CoefCol25 { get; set; }
        public decimal? CoefCol26 { get; set; }
        public decimal? CoefCol27 { get; set; }
        public decimal? CoefCol28 { get; set; }
        public decimal? CoefCol29 { get; set; }
        public decimal? CoefCol30 { get; set; }
        public decimal? CoefCol31 { get; set; }
        public decimal? CoefCol32 { get; set; }
        public decimal? CoefCol33 { get; set; }
        public decimal? CoefCol34 { get; set; }
        public decimal? CoefCol35 { get; set; }
        public decimal? CoefCol36 { get; set; }
        public decimal? CoefCol37 { get; set; }
        public decimal? CoefCol38 { get; set; }
        public decimal? CoefCol39 { get; set; }
        public decimal? CoefCol40 { get; set; }
        public byte? Numpromotioncs { get; set; }
        public bool? ApCs { get; set; }
        public string TypeCol41 { get; set; }
        public string IdCol41 { get; set; }
        public string NomCol41 { get; set; }
        public decimal? MoyCol41 { get; set; }
        public string EtatCol41 { get; set; }
        public string TypeCol42 { get; set; }
        public string IdCol42 { get; set; }
        public string NomCol42 { get; set; }
        public decimal? MoyCol42 { get; set; }
        public string EtatCol42 { get; set; }
        public string TypeCol43 { get; set; }
        public string IdCol43 { get; set; }
        public string NomCol43 { get; set; }
        public decimal? MoyCol43 { get; set; }
        public string EtatCol43 { get; set; }
        public string TypeCol44 { get; set; }
        public string IdCol44 { get; set; }
        public string NomCol44 { get; set; }
        public decimal? MoyCol44 { get; set; }
        public string EtatCol44 { get; set; }
        public string TypeCol45 { get; set; }
        public string IdCol45 { get; set; }
        public string NomCol45 { get; set; }
        public decimal? MoyCol45 { get; set; }
        public string EtatCol45 { get; set; }
        public string TypeCol46 { get; set; }
        public string IdCol46 { get; set; }
        public string NomCol46 { get; set; }
        public decimal? MoyCol46 { get; set; }
        public string EtatCol46 { get; set; }
        public string TypeCol47 { get; set; }
        public string IdCol47 { get; set; }
        public string NomCol47 { get; set; }
        public decimal? MoyCol47 { get; set; }
        public string EtatCol47 { get; set; }
        public string TypeCol48 { get; set; }
        public string IdCol48 { get; set; }
        public string NomCol48 { get; set; }
        public decimal? MoyCol48 { get; set; }
        public string EtatCol48 { get; set; }
        public string TypeCol49 { get; set; }
        public string IdCol49 { get; set; }
        public string NomCol49 { get; set; }
        public decimal? MoyCol49 { get; set; }
        public string EtatCol49 { get; set; }
        public string TypeCol50 { get; set; }
        public string IdCol50 { get; set; }
        public string NomCol50 { get; set; }
        public decimal? MoyCol50 { get; set; }
        public string EtatCol50 { get; set; }
        public byte? NbHeureCol41 { get; set; }
        public byte? NbHeureCol42 { get; set; }
        public byte? NbHeureCol43 { get; set; }
        public byte? NbHeureCol44 { get; set; }
        public byte? NbHeureCol45 { get; set; }
        public byte? NbHeureCol46 { get; set; }
        public byte? NbHeureCol47 { get; set; }
        public byte? NbHeureCol48 { get; set; }
        public byte? NbHeureCol49 { get; set; }
        public byte? NbHeureCol50 { get; set; }
        public decimal? CoefCol41 { get; set; }
        public decimal? CoefCol42 { get; set; }
        public decimal? CoefCol43 { get; set; }
        public decimal? CoefCol44 { get; set; }
        public decimal? CoefCol45 { get; set; }
        public decimal? CoefCol46 { get; set; }
        public decimal? CoefCol47 { get; set; }
        public decimal? CoefCol48 { get; set; }
        public decimal? CoefCol49 { get; set; }
        public decimal? CoefCol50 { get; set; }
        public string CodeDecision { get; set; }
        public string LibDecision { get; set; }
        public decimal? Moygen { get; set; }
        public string EtatCol40 { get; set; }
        public string Credit1 { get; set; }
        public string Credit2 { get; set; }
        public string TypePv { get; set; }
        public string CodeDecisionRat2 { get; set; }
        public string LibDecisionRat2 { get; set; }
        public string CodeDecisionRatt { get; set; }
        public string LibDecisionRatt { get; set; }
        public string CreditRouge { get; set; }
        public string CreditVert { get; set; }
        public decimal? Moyratt { get; set; }
        public byte? NbHeureCol51 { get; set; }
        public byte? NbHeureCol52 { get; set; }
        public byte? NbHeureCol53 { get; set; }
        public byte? NbHeureCol54 { get; set; }
        public byte? NbHeureCol55 { get; set; }
        public byte? NbHeureCol56 { get; set; }
        public byte? NbHeureCol57 { get; set; }
        public byte? NbHeureCol58 { get; set; }
        public byte? NbHeureCol59 { get; set; }
        public byte? NbHeureCol60 { get; set; }
        public decimal? CoefCol51 { get; set; }
        public decimal? CoefCol52 { get; set; }
        public decimal? CoefCol53 { get; set; }
        public decimal? CoefCol54 { get; set; }
        public decimal? CoefCol55 { get; set; }
        public decimal? CoefCol56 { get; set; }
        public decimal? CoefCol57 { get; set; }
        public decimal? CoefCol58 { get; set; }
        public decimal? CoefCol59 { get; set; }
        public decimal? CoefCol60 { get; set; }
        public string TypeCol51 { get; set; }
        public string IdCol51 { get; set; }
        public string NomCol51 { get; set; }
        public decimal? MoyCol51 { get; set; }
        public string EtatCol51 { get; set; }
        public string TypeCol52 { get; set; }
        public string IdCol52 { get; set; }
        public string NomCol52 { get; set; }
        public decimal? MoyCol52 { get; set; }
        public string EtatCol52 { get; set; }
        public string TypeCol53 { get; set; }
        public string IdCol53 { get; set; }
        public string NomCol53 { get; set; }
        public decimal? MoyCol53 { get; set; }
        public string EtatCol53 { get; set; }
        public string TypeCol54 { get; set; }
        public string IdCol54 { get; set; }
        public string NomCol54 { get; set; }
        public decimal? MoyCol54 { get; set; }
        public string EtatCol54 { get; set; }
        public string TypeCol55 { get; set; }
        public string IdCol55 { get; set; }
        public string NomCol55 { get; set; }
        public decimal? MoyCol55 { get; set; }
        public string EtatCol55 { get; set; }
        public string TypeCol56 { get; set; }
        public string IdCol56 { get; set; }
        public string NomCol56 { get; set; }
        public decimal? MoyCol56 { get; set; }
        public string EtatCol56 { get; set; }
        public string TypeCol57 { get; set; }
        public string IdCol57 { get; set; }
        public string NomCol57 { get; set; }
        public decimal? MoyCol57 { get; set; }
        public string EtatCol57 { get; set; }
        public string TypeCol58 { get; set; }
        public string IdCol58 { get; set; }
        public string NomCol58 { get; set; }
        public decimal? MoyCol58 { get; set; }
        public string EtatCol58 { get; set; }
        public string TypeCol59 { get; set; }
        public string IdCol59 { get; set; }
        public string NomCol59 { get; set; }
        public decimal? MoyCol59 { get; set; }
        public string EtatCol59 { get; set; }
        public string TypeCol60 { get; set; }
        public string IdCol60 { get; set; }
        public string NomCol60 { get; set; }
        public decimal? MoyCol60 { get; set; }
        public string EtatCol60 { get; set; }
        public string NatureUe1 { get; set; }
        public string NatureUe2 { get; set; }
        public string NatureUe3 { get; set; }
        public string NatureUe4 { get; set; }
        public string NatureUe5 { get; set; }
        public string NatureUe6 { get; set; }
        public string NatureUe7 { get; set; }
        public string NatureUe8 { get; set; }
        public string NatureUe9 { get; set; }
        public string NatureUe10 { get; set; }
        public string NatureUe11 { get; set; }
        public string NatureUe12 { get; set; }
        public string NatureUe13 { get; set; }
        public string NatureUe14 { get; set; }
        public string NatureUe15 { get; set; }
        public string NatureUe16 { get; set; }
        public string NatureUe17 { get; set; }
        public string NatureUe18 { get; set; }
        public string NatureUe19 { get; set; }
        public string NatureUe20 { get; set; }
        public string NatureUe21 { get; set; }
        public string NatureUe22 { get; set; }
        public string NatureUe23 { get; set; }
        public string NatureUe24 { get; set; }
        public string NatureUe25 { get; set; }
        public string NatureUe26 { get; set; }
        public string NatureUe27 { get; set; }
        public string NatureUe28 { get; set; }
        public string NatureUe29 { get; set; }
        public string NatureUe30 { get; set; }
        public string NatureUe31 { get; set; }
        public string NatureUe32 { get; set; }
        public string NatureUe33 { get; set; }
        public string NatureUe34 { get; set; }
        public string NatureUe35 { get; set; }
        public string NatureUe36 { get; set; }
        public string NatureUe37 { get; set; }
        public string NatureUe38 { get; set; }
        public string NatureUe39 { get; set; }
        public string NatureUe40 { get; set; }
        public string NatureUe41 { get; set; }
        public string NatureUe42 { get; set; }
        public string NatureUe43 { get; set; }
        public string NatureUe44 { get; set; }
        public string NatureUe45 { get; set; }
        public string NatureUe46 { get; set; }
        public string NatureUe47 { get; set; }
        public string NatureUe48 { get; set; }
        public string NatureUe49 { get; set; }
        public string NatureUe50 { get; set; }
        public string NatureUe51 { get; set; }
        public string NatureUe52 { get; set; }
        public string NatureUe53 { get; set; }
        public string NatureUe54 { get; set; }
        public string NatureUe55 { get; set; }
        public string NatureUe56 { get; set; }
        public string NatureUe57 { get; set; }
        public string NatureUe58 { get; set; }
        public string NatureUe59 { get; set; }
        public string NatureUe60 { get; set; }
    }
}
